"""Python async client for Airplast AirApp backend APIs."""

from .client import AirplastApiClient, AirplastClient, AirplastResponse
from .exceptions import AirplastAuthError, AirplastError, AirplastRequestError
from .openapi_models import (
    # enums
    AirQuality,
    DayOfWeek,
    DeviceRole,
    DeviceSubtype,
    DeviceType,
    FanSpeed,
    FilterStatus,
    HumidityLevel,
    LightSensorLevel,
    LightSensorLevelEnum,
    OperatingMode,
    PacketType,
    ResetType,
    RoomNames,
    ScheduleState,
    UserOperationType,
    # request models
    AddHouseRequest,
    AddNewDeviceRequest,
    AuthenticateRequest,
    ChangeModeRequest,
    ChangeUsernameRequest,
    ConfirmRegisterRequest,
    NewOperationTokenRequest,
    NewZoneWithRoomsRequest,
    RecoverPasswordRequest,
    RegisterRequestWs,
    RenameDeviceRequest,
    RenameHouseRequest,
    RenameZoneRequest,
    ResetDeviceRequest,
    SetHouseTimezoneRequest,
    TimeSlot,
    UpdateFirstLastNameRequest,
    UpdatePasswordRequest,
    # response models
    AuthenticateResponse,
    Device,
    FeatureFlagsResponse,
    GeminiDeviceInfo,
    House,
    HouseDevicesInfo,
    HouseInfo,
    ProblemDetails,
    Room,
    Schedule,
    StatusPacket,
    TimeSlotModificationResult,
    TokenInfoResponse,
    TokenRefreshResponse,
    UserDetailsResponse,
    Zone,
    ZoneDeviceInfo,
    # backwards-compat aliases
    AddZoneRequest,
    ChangeEmailRequest,
    ChangePasswordRequest,
    CompleteRecoverPasswordRequest,
    CompleteRegistrationRequest,
    LoginRequest,
    UpdateUserDetailsRequest,
)

__all__ = [
    # client
    "AirplastApiClient",
    "AirplastClient",
    "AirplastResponse",
    # exceptions
    "AirplastAuthError",
    "AirplastError",
    "AirplastRequestError",
    # enums
    "AirQuality",
    "DayOfWeek",
    "DeviceRole",
    "DeviceSubtype",
    "DeviceType",
    "FanSpeed",
    "FilterStatus",
    "HumidityLevel",
    "LightSensorLevel",
    "LightSensorLevelEnum",
    "OperatingMode",
    "PacketType",
    "ResetType",
    "RoomNames",
    "ScheduleState",
    "UserOperationType",
    # request models
    "AddHouseRequest",
    "AddNewDeviceRequest",
    "AuthenticateRequest",
    "ChangeModeRequest",
    "ChangeUsernameRequest",
    "ConfirmRegisterRequest",
    "NewOperationTokenRequest",
    "NewZoneWithRoomsRequest",
    "RecoverPasswordRequest",
    "RegisterRequestWs",
    "RenameDeviceRequest",
    "RenameHouseRequest",
    "RenameZoneRequest",
    "ResetDeviceRequest",
    "SetHouseTimezoneRequest",
    "TimeSlot",
    "UpdateFirstLastNameRequest",
    "UpdatePasswordRequest",
    # response models
    "AuthenticateResponse",
    "Device",
    "FeatureFlagsResponse",
    "GeminiDeviceInfo",
    "House",
    "HouseDevicesInfo",
    "HouseInfo",
    "ProblemDetails",
    "Room",
    "Schedule",
    "StatusPacket",
    "TimeSlotModificationResult",
    "TokenInfoResponse",
    "TokenRefreshResponse",
    "UserDetailsResponse",
    "Zone",
    "ZoneDeviceInfo",
    # backwards-compat aliases
    "AddZoneRequest",
    "ChangeEmailRequest",
    "ChangePasswordRequest",
    "CompleteRecoverPasswordRequest",
    "CompleteRegistrationRequest",
    "LoginRequest",
    "UpdateUserDetailsRequest",
]